controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    effort_controller1:
      type: effort_controllers/JointGroupEffortController

effort_controller1:
  ros__parameters:
    joints:
      - cart_rail_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort


